- Fixed a bug in collision detection which happend when 2 wrecks where   overlapping. This caused permanent collisions, which in turn avoided to call   dtProceed and therefore avoided the needed update of the data (Bernhard). - Fixed: non ending races because of failing virtual crane, was a floating   point error accumulation problem in simu.cpp (Bernhard). - Barrier has now a field with normal used for barrier collision detection,   reworked SimCarCollideXYScene, collide.cpp (Bernhard). - Added vector classes, such that all berniw/bt derivates can use the same   copy, instead of having a copy in each bot (Bernhard). - Collision code refactoring/cleanup, removed doubled code, etc. (Bernhard). - Initial wall collision support, good enough for now, but needs   improvment and more testing. The damage is currently set very low, such   that the robots have some time to adopt (Bernhard). - Fixed skid sound at low speeds (Christos, Bernhard). - Fixed scroll lists numbering with more than 100 entries (Bernhard). - Enabled configure checking for OpenAL (Bernhard). - Fixed skidmarks when driving in reverse, bug introduced by me when enabling   backface-culling for skids (Christos, Bernhard). - Added trackgen option to just calculate the track parameters (Charalampos). - Increased a "margin" in trackgens track.cpp, will need further inverstigation   (Charalampos).

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6063,8 +6063,152 @@ echo "$as_me: error: Can't find plib/ssg.h. PLIB can be found on http://plib.sou
 fi
 
 
+if test "${ac_cv_header_AL_al_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for AL/al.h" >&5
+echo $ECHO_N "checking for AL/al.h... $ECHO_C" >&6
+if test "${ac_cv_header_AL_al_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_AL_al_h" >&5
+echo "${ECHO_T}$ac_cv_header_AL_al_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking AL/al.h usability" >&5
+echo $ECHO_N "checking AL/al.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <AL/al.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
 
-#AC_CHECK_HEADER(AL/al.h,, AC_MSG_ERROR([Can't find AL/al.h. OpenAL can be found on http://www.openal.org/]))
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking AL/al.h presence" >&5
+echo $ECHO_N "checking AL/al.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <AL/al.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_cxx_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_cxx_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: AL/al.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: AL/al.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: AL/al.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: AL/al.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: AL/al.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: AL/al.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: AL/al.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: AL/al.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: AL/al.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: AL/al.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: AL/al.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: AL/al.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: AL/al.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: AL/al.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: AL/al.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: AL/al.h: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------------ ##
+## Report this to the AC_PACKAGE_NAME lists.  ##
+## ------------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for AL/al.h" >&5
+echo $ECHO_N "checking for AL/al.h... $ECHO_C" >&6
+if test "${ac_cv_header_AL_al_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_AL_al_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_AL_al_h" >&5
+echo "${ECHO_T}$ac_cv_header_AL_al_h" >&6
+
+fi
+if test $ac_cv_header_AL_al_h = yes; then
+  :
+else
+  { { echo "$as_me:$LINENO: error: Can't find AL/al.h. OpenAL can be found on http://www.openal.org/" >&5
+echo "$as_me: error: Can't find AL/al.h. OpenAL can be found on http://www.openal.org/" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
 
 #AC_CHECK_HEADER(X11/Xfuncproto.h,, AC_MSG_ERROR([Can't find X11/Xfuncproto.h. Please check config.log and if you can't solve the problem send the file totorcs-users@lists.sourceforge.net with the subject \"torcs compilation problem\"]))
 #AC_CHECK_HEADER(X11/extensions/randr.h,, AC_MSG_ERROR([Can't find X11/extensions/randr.h. Please check config.log and if you can't solve the problem send the file to torcs-users@lists.sourceforge.net with the subject \"torcs compilation problem\"]))
@@ -6926,6 +7070,84 @@ _ACEOF
 else
   { { echo "$as_me:$LINENO: error: Can't find libXrandr. Please check config.log and if you can't solve the problem send the file to torcs-users@lists.sourceforge.net with the subject \"torcs compilation problem\"" >&5
 echo "$as_me: error: Can't find libXrandr. Please check config.log and if you can't solve the problem send the file to torcs-users@lists.sourceforge.net with the subject \"torcs compilation problem\"" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+echo "$as_me:$LINENO: checking for alEnable in -lopenal" >&5
+echo $ECHO_N "checking for alEnable in -lopenal... $ECHO_C" >&6
+if test "${ac_cv_lib_openal_alEnable+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lopenal  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char alEnable ();
+int
+main ()
+{
+alEnable ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_openal_alEnable=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_openal_alEnable=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_openal_alEnable" >&5
+echo "${ECHO_T}$ac_cv_lib_openal_alEnable" >&6
+if test $ac_cv_lib_openal_alEnable = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBOPENAL 1
+_ACEOF
+
+  LIBS="-lopenal $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: Can't find AL/al.h. OpenAL can be found on http://www.openal.org/" >&5
+echo "$as_me: error: Can't find AL/al.h. OpenAL can be found on http://www.openal.org/" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
