Version number to 1.3.1, fixed #1674545.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2085,7 +2085,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=torcs
- VERSION=1.3.1-test1
+ VERSION=1.3.1
 
 
 cat >>confdefs.h <<_ACEOF
@@ -7644,8 +7644,8 @@ _ACEOF
   LIBS="-lXrender $LIBS"
 
 else
-  { { echo "$as_me:$LINENO: error: Can't find libXrandr. Please check config.log and if you can't solve the problem send the file to torcs-users@lists.sourceforge.net with the subject \"torcs compilation problem\"" >&5
-echo "$as_me: error: Can't find libXrandr. Please check config.log and if you can't solve the problem send the file to torcs-users@lists.sourceforge.net with the subject \"torcs compilation problem\"" >&2;}
+  { { echo "$as_me:$LINENO: error: Can't find libXrender. Please check config.log and if you can't solve the problem send the file to torcs-users@lists.sourceforge.net with the subject \"torcs compilation problem\"" >&5
+echo "$as_me: error: Can't find libXrender. Please check config.log and if you can't solve the problem send the file to torcs-users@lists.sourceforge.net with the subject \"torcs compilation problem\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
